---
test_name: Fluxo de tarefas por usuario

marks:
  - parametrize:
      key: todo_id
      vals:
        - 1
        - 5
        - 15

stages:
  - name: Buscar tarefa especifica
    request:
      url: "https://jsonplaceholder.typicode.com/todos/{todo_id}"
      method: GET
    response:
      status_code: 200
      save:
        json:
          id_do_usuario: userId

  - name: Buscar todas as tarefas do usuario
    request:
      url: "https://jsonplaceholder.typicode.com/todos"
      method: GET
      params:
        userId: "{id_do_usuario}"
    response:
      status_code: 200
      verify_response_with:
        function: utils:validar_lista_tarefas
